---
title: "interventions"
author: "Hannah Chang"
date: '2022-07-19'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#--Set working directory
setwd('C:/Users/hanna/OneDrive - London School of Hygiene and Tropical Medicine/3_summer/script/fin/epic-om/data')

#--Install necessary packages
pacman::p_load(tidyverse, rio, stringr, lubridate, gridExtra, ggpubr, reshape2)
```

1. c2.2
1-1. Mobility Index

```{r}
ggl_mob_raw <- import('./google_mobility.csv')

ggl_mob_kor <- ggl_mob_raw %>%
  filter(Code=='KOR') %>%
  mutate(Date = lubridate::mdy(Day)) %>%
  filter(Date > '2021-10-31' & Date < '2022-07-01') %>%
  dplyr::select(Date, grocery_and_pharmacy, residential, retail_and_recreation, transit_stations, workplaces)

ggl_mob_raw %>%
  mutate(Date = lubridate::mdy(Day)) %>%
  summarize(min = min(Date))

```

1-2. Work
```{r}
mob_work <- ggl_mob_kor %>%
  dplyr::select(Date, workplaces) 

mob_work <- mob_work %>%
  mutate(time = seq(0:241))

mob_work %>%
  filter(time < 169) %>%
  summarise(pre_lifting_mean = mean(workplaces, na.rm=T), sd = sd(workplaces))
  # pre_lifting_mean    sd
  #          -3.646  8.248
mob_work %>%
  filter(time < 169) %>%
  summarise(pre_lifting_min = min(workplaces))
  #  pre_lifting_max
  #         -40

mob_work %>%
  filter(time > 168) %>%
  summarise(post_lifting_mean = mean(workplaces, na.rm=T), sd = sd(workplaces))
  #  post_lifting_mean    sd
  #              4.338 5.563


#--C2 work closure level 2 to 0 at day 169
c2_from2_to0 <- ggplot() +
  geom_line(data = mob_work, aes(x=time, y=workplaces), size=0.5)+
  geom_vline(xintercept=169, colour = 'grey', alpha=0.5)+
  geom_segment(aes(x=0, xend=168, y=-3.646, yend=-3.646), colour = 'red', alpha=0.8) +
  geom_segment(aes(x=169, xend=241, y=4.338, yend=4.338), colour = 'blue', alpha=0.8)+
  theme_classic2() +
  annotate(geom = "text", x=240, y=3, label="(+4.338)", colour="blue", size=3)+
    annotate(geom = "text", x=10, y=-5, label="(-3.646)", colour="red", size=3)+
    annotate(geom = "text", x=70, y=-50, label="level 2", colour="grey", size=3, alpha=0.8)+
    annotate(geom = "text", x=220, y=-50, label="level 0", colour="grey", size=3, alpha=0.8)+
  ylab('Google Mobility Index')+
  xlab('Time (day)')

c2_from2_to0
```

2. c1.1
```{r}
##Create school attendance data
sch_atd <- data.frame(
  date = c('2021-11-02','2021-11-04','2021-11-09', '2021-11-11', '2021-11-16','2021-11-18', '2021-11-23','2021-11-25','2021-11-30','2021-12-09','2021-12-14'),
  attendance = c(81.5,81.6, 79.2,80,63.6,63.6, 91.6, 91.1,90.6,87.8, 87.2)
)
  #From the press release of the Ministry of Education

sch_atd <- sch_atd %>%
  mutate(date2 = as.Date(date), attendance2=attendance/100)

##Plot 
ggplot(data = sch_atd, aes(x=date2, y=attendance2)) +
  geom_bar(stat="identity", alpha=0.5) + 
  geom_vline(xintercept=as.Date('2021-11-21'), alpha = 0.5)+
  geom_segment(aes(x=as.Date('2021-11-01'), xend=as.Date('2021-11-19'), y=0.75, yend=0.75), colour = 'blue')+
  geom_segment(aes(x=as.Date('2021-11-23'), xend=as.Date('2021-12-14'), y=0.896, yend=0.896), colour = 'red')+
  ylab('Pre / primary / secondary school attendance')+
  xlab('Date')+
  scale_y_continuous(breaks = seq(0, 1.0, 0.2))

##Compare average attendance with and without c1.1
sch_atd %>% 
  filter(date2 < '2021-11-22') %>%
  summarise(mean = mean(attendance2, na.rm=T))
  #avg attendance when school closure was recommended = 0.7491667
  #attendance = no. students who went to school out of total students in pre / primary / secondary school 

sch_atd %>% 
  filter(date2 > '2021-11-21') %>%
  summarise(mean = mean(attendance2, na.rm=T))
  #avg attendance when there was no restriction on school closure = 0.8966

```

3. c4.4

	data_contacts_no1 <- data_contacts
	data_contacts_no2 <- data_contacts
	
	data_contacts_no1$e_other[data_contacts_no1$e_other>20] <- 20
	data_contacts_no2$e_other[data_contacts_no2$e_other>10] <- 10
	
	mean(data_contacts$e_other)
	mean(data_contacts_no1$e_other)
	mean(data_contacts_no2$e_other)
	
	Ref: Dr. Adam Kucharski

```{r}
#--Import the BBC Pandemic dataset for adults (18+ years)
ct_a <- read.csv('https://raw.githubusercontent.com/adamkucharski/2020-cov-tracing/master/data/contact_distributions_o18.csv')

ct_a1 <- ct_a

#--Restricting gathering to 10 ppl
ct_a1$e_other[ct_a1$e_other>10] <- 10

#---avg decrease in other contact
mu_a <- mean(ct_a$e_other)
mu_a1 <- mean(ct_a1$e_other)

#---Effect of c4.4= 1- proportion decrease
c4.4_a <- 1-(mu_a-mu_a1)/mu_a

```

```{r}
#--Import the BBC Pandemic dataset for children (<18 years)
ct_y <- read.csv('https://raw.githubusercontent.com/adamkucharski/2020-cov-tracing/master/data/contact_distributions_u18.csv')

ct_y1 <- ct_y

#--Restricting gathering to 10 ppl
ct_y1$e_other[ct_y1$e_other>10] <- 10

#---avg decrease in other contact
mu_y <- mean(ct_y$e_other)
mu_y1 <- mean(ct_y1$e_other)

#---Effect of c4.4= 1- proportion decrease
c4.4_y <- 1-(mu_y-mu_y1)/mu_y
```

4. c3.1
```{r}
#--Import the BBC Pandemic dataset for adults (18+ years)
ct_a2 <- ct_a

#--Restricting gathering to 15 ppl
ct_a2$e_other[ct_a2$e_other>15] <- 15

#---avg decrease in other contact
mu_a2 <- mean(ct_a2$e_other)

#---Effect of c3.1= 1- proportion decrease
c3.1_a <- 1-(mu_a-mu_a2)/mu_a

```

```{r}
#--Import the BBC Pandemic dataset for children (<18 years)
ct_y2 <- ct_y

#--Restricting gathering to 15 ppl
ct_y2$e_other[ct_y2$e_other>15] <- 15

#---avg decrease in other contact
mu_y2 <- mean(ct_y2$e_other)

#---Effect of c3.1= 1- proportion decrease
c3.1_y <- 1-(mu_y-mu_y2)/mu_y
```